CREATE TABLE Alunos(
    IdAluno INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NomeAluno VARCHAR NOT NULL,
    IdCurso INTEGER NOT NULL,
    AnoIngresso INTEGER NOT NULL,
    FOREIGN KEY (IdCurso)
        REFERENCES Cursos (IdCurso)
);

CREATE TABLE Avaliacoes(
    IdAvaliacao INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    IdAluno INTEGER NOT NULL,
    IdAula INTEGER NOT NULL,
    Nota INTEGER NOT NULL,
    FOREIGN KEY (IdAluno)
        REFERENCES Alunos (IdAluno),
    FOREIGN KEY (IdAula)
        REFERENCES Aulas (IdAula)
);

CREATE TABLE Aulas(
    IdAula INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    IdDisc INTEGER NOT NULL,
    IdCurso INTEGER NOT NULL,
    IdProf INTEGER NOT NULL,
    Ano INTEGER NOT NULL,
    FOREIGN KEY (IdProf)
        REFERENCES Professores (IdProf),
    FOREIGN KEY (IdCurso)
        REFERENCES Cursos (IdCurso),
    FOREIGN KEY (IdDisc)
        REFERENCES Disciplinas (IdDisc)
);

CREATE TABLE Centros(
    IdCentro INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    Nome VARCHAR NOT NULL
);

CREATE TABLE Cursos(
    IdCurso INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NomeCurso VARCHAR NOT NULL,
    IdDepto INTEGER NOT NULL,
    FOREIGN KEY (IdDepto)
        REFERENCES Departamentos (IdDepto)
);

CREATE TABLE Departamentos(
    IdDepto INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NomeDepto VARCHAR NOT NULL,
    IdCentro INTEGER NOT NULL,
    FOREIGN KEY (IdCentro)
        REFERENCES Centros (IdCentro)
);

CREATE TABLE Disciplinas(
    IdDisc INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NomeDisc VARCHAR NOT NULL
);

CREATE TABLE Matriculas(
    IdMatricula INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    IdAluno INTEGER NOT NULL,
    IdAula INTEGER NOT NULL,
    FOREIGN KEY (IdAluno)
        REFERENCES Alunos (IdAluno),
    FOREIGN KEY (IdAula)
        REFERENCES Aulas (IdAula)
);
CREATE TABLE Presenca(
    IdPresenca INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    IdAluno INTEGER NOT NULL,
    IdAula INTEGER NOT NULL,
    Presenca INTEGER NOT NULL,
    FOREIGN KEY (IdAluno)
        REFERENCES Alunos (IdAluno),
    FOREIGN KEY (IdAula)
        REFERENCES Aulas (IdAula)
);
CREATE TABLE Professores(
    IdProf INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NomeProf VARCHAR NOT NULL,
    IdDepto INTEGER NOT NULL,
    FOREIGN KEY (IdDepto)
        REFERENCES Departamentos (IdDepto)
);
CREATE TABLE Qualificacoes(
    IdQual INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    IdProf INTEGER NOT NULL,
    IdDisc INTEGER NOT NULL,
    FOREIGN KEY (IdProf)
        REFERENCES Professores (IdProf)
    FOREIGN KEY (IdDisc)
        REFERENCES Disciplinas (IdDisc)
);